name: interview_tracker
description: "A comprehensive Job Interview Tracker application"
publish_to: "none"
version: 1.2.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
